In [3]:
!pip install numpy

# Single Dimensional Array 

import numpy as np
n1=np.array([10,20,30,40])
n1

In [15]:
type(n1)


numpy.ndarray

## Multidimenional Numpy Array


In [16]:
import numpy as np
n2=np.array([[10,20,30],[10,80,90],[30,50,60]])
print(n2)

[[10 20 30]
 [10 80 90]
 [30 50 60]]


In [ ]:
# Initilize NumPy Array With Zeros

In [19]:
n3=np.zeros((2,3))
print(n3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
n4=np.zeros((9,9))
print(n4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Initiliztion a array of matrix with full then

In [24]:
n5=np.full((3,3),9)
print(n5)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


# Initilization of Numpy array within a range

In [28]:
n6=np.arange(10,20)
print(n6)

[10 11 12 13 14 15 16 17 18 19]


# Initilization of the NumPy array with the skip numbers

In [29]:
n7=np.arange(1,20,2)
print(n7)

[ 1  3  5  7  9 11 13 15 17 19]


# Initilization Numpy array with the random numbers

In [36]:
n8=np.random.randint(100,1000,10)
print(n8)

[220 820 753 167 491 660 743 352 469 190]


# Initilization the array shape changes in a fraction of seconds.

In [42]:
n9=np.array([[10,20,30],[10,80,90],[30,50,80],[20,40,50]])
print(n9)

[[10 20 30]
 [10 80 90]
 [30 50 80]
 [20 40 50]]


In [43]:
n9.shape

(4, 3)

In [48]:
n9.shape=(3,4)
print(n9)

[[10 20 30 10]
 [80 90 30 50]
 [80 20 40 50]]


# Joining Numpy Array

In [49]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
b=np.array([5,10,15,20,25,30,35,40,55,60])


In [51]:
np.vstack((a,b))

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  5,  10,  15,  20,  25,  30,  35,  40,  55,  60]])

In [52]:
np.hstack((a,b))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,   5,  10,  15,
        20,  25,  30,  35,  40,  55,  60])

In [53]:
np.column_stack((a,b))

array([[ 10,   5],
       [ 20,  10],
       [ 30,  15],
       [ 40,  20],
       [ 50,  25],
       [ 60,  30],
       [ 70,  35],
       [ 80,  40],
       [ 90,  55],
       [100,  60]])